id: I0247CB7B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:51:45+00:00'
last_modified: '2022-06-08T06:27:23.072101+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017157
  title: གནས་ཆེན་ཁ་བ་དཀར་པོའི་བསང་མཆོད་དང་གནས་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9A36:
      image_group_id: I00EGS1017161
      title: ''
      total_pages: 142
      order: 1
      base_file: 9A36.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
